Postgres Connection with C: src/helpers.c File Reference
helpers.c File Reference
#include "../inc/helpers.h"
#include <stdbool.h>
#include <stdio.h>
#include <string.h>
Macros
#define RED "\x1B[31m"
#define GRN "\x1B[32m"
#define YEL "\x1B[33m"
#define BLU "\x1B[34m"
#define MAG "\x1B[35m"
#define CYN "\x1B[36m"
#define WHT "\x1B[37m"
#define RESET "\x1B[0m"
Functions
void print (char *text, char *color)
Função responsável por dar cor a um printf.
bool strIsEqual (const char *str1, const char *str2)
Faz uma comparação de strings e retorna um boolean.
void printLine (char *color)
Printa uma linha com a cor escolhida.
char * getString ()
Função para pegar uma string do usuário.
void clearBuffer ()
Função para poder limpar o buffer de entrada.
int getRowNumber ()
Função para poder pegar um inteiro do usuário.
void getColumns (char tableColumns[][2][100], int rowNumber)
Pega o nome e o tipo da coluna.
char * makeQuery (char *tableName, char tableColumns[][2][100], int fieldQuantity)
Cria a query SQL.
char * buildQueryWithFilter (const char *tableName)
Cria a query SQL com os filtros necessários para o SELECT.
Variables
int errno
Macro Definition Documentation
BLU
#define BLU "\x1B[34m"
CYN
#define CYN "\x1B[36m"
GRN
#define GRN "\x1B[32m"
MAG
#define MAG "\x1B[35m"
RED
#define RED "\x1B[31m"
RESET
#define RESET "\x1B[0m"
WHT
#define WHT "\x1B[37m"
YEL
#define YEL "\x1B[33m"
Function Documentation
buildQueryWithFilter()
char * buildQueryWithFilter (const char * tableName)
Cria a query SQL com os filtros necessários para o SELECT.
References print().
Referenced by showTable().
clearBuffer()
void clearBuffer ()
Função para poder limpar o buffer de entrada.
Referenced by createNewTable(), getColumns(), and insertData().
getColumns()
void getColumns (char tableColumns[][2][100], int rowNumber)
Pega o nome e o tipo da coluna.
References clearBuffer().
Referenced by createNewTable().
getRowNumber()
int getRowNumber ()
Função para poder pegar um inteiro do usuário.
References print().
Referenced by createNewTable().
getString()
char * getString ()
Função para pegar uma string do usuário.
References print(), and printLine().
Referenced by createNewTable(), insert(), options(), and showTable().
makeQuery()
char * makeQuery (char * tableName, char tableColumns[][2][100], int fieldQuantity)
Cria a query SQL.
Referenced by createNewTable().
print()
void print (char * text, char * color)
Função responsável por dar cor a um printf.
References BLU, CYN, GRN, MAG, RED, RESET, strIsEqual(), WHT, and YEL.
Referenced by buildQueryWithFilter(), closeConnection(), createNewTable(), getRowNumber(), getString(), insertData(), options(), printLine(), showTable(), showTables(), showTableSpecifications(), start(), and verifyCreateTable().
printLine()
void printLine (char * color)
Printa uma linha com a cor escolhida.
References print().
Referenced by getString(), options(), and start().
strIsEqual()
bool strIsEqual (const char * str1, const char * str2)
Faz uma comparação de strings e retorna um boolean.
Referenced by print().
Variable Documentation
errno
int errno extern