Postgres Connection with C: src/psql.c File Reference
psql.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include "../inc/helpers.h"
#include "../inc/psql.h"
#include "/opt/homebrew/opt/libpq/include/libpq-fe.h"
Classes
struct _connectionInfo
Functions
ConnectionInfo * getConnectionInfo ()
Essa função cria uma struct com as informações necessárias para a conexão do banco de dados utilizando a struct de informações.
ConnectionInfo * mockConnectionInfo ()
Função para mockar os dados de conexão.
PGconn * connectDB ()
Essa função faz a conexão com o banco de dados e retorna o status da conexão.
void closeConnection (PGconn *conn)
Essa função encerra a conexão com o banco de dados.
PGresult * getTablesQuery (PGconn *conn)
Essa função busca as tabelas públicas do banco de dados registrado.
PGresult * exeQuery (PGconn *conn, const char *query)
Função que recebe a conexão do banco de dados e uma query, executa essa query nessa conexão e retorna.
PGresult * getTableSpecifications (PGconn *conn, const char *tableName)
Pega as especificações de uma tabela,recebendo a conexão e o nome da tabela.
void verifyCreateTable (PGresult *result, PGconn *connection)
Verifica a criação da tabela.
void insertData (PGconn *conn, PGresult *res, const char *tableName)
void displayTableResult (PGconn *conn, PGresult *res, const char *tableName)
void displayQueryResult (PGresult *res)
Função para exibir o resultado da query.
void checkDeleteResult (PGresult *res)
Função para checkar se a query de delete foi bem sucedida.
Function Documentation
checkDeleteResult()
void checkDeleteResult (PGresult * res)
Função para checkar se a query de delete foi bem sucedida.
References print().
Referenced by delete().
closeConnection()
void closeConnection (PGconn * conn)
Essa função encerra a conexão com o banco de dados.
References print().
Referenced by options().
connectDB()
PGconn * connectDB ()
Essa função faz a conexão com o banco de dados e retorna o status da conexão.
References _connectionInfo::database, _connectionInfo::host, mockConnectionInfo(), _connectionInfo::password, _connectionInfo::port, and _connectionInfo::user.
Referenced by start().
displayQueryResult()
void displayQueryResult (PGresult * res)
Função para exibir o resultado da query.
Referenced by showTable().
displayTableResult()
void displayTableResult (PGconn * conn, PGresult * res, const char * tableName)
exeQuery()
PGresult * exeQuery (PGconn * conn, const char * query)
Função que recebe a conexão do banco de dados e uma query, executa essa query nessa conexão e retorna.
Referenced by createNewTable(), delete(), getTableSpecifications(), and showTable().
getConnectionInfo()
ConnectionInfo * getConnectionInfo ()
Essa função cria uma struct com as informações necessárias para a conexão do banco de dados utilizando a struct de informações.
References _connectionInfo::database, _connectionInfo::host, _connectionInfo::password, _connectionInfo::port, and _connectionInfo::user.
getTableSpecifications()
PGresult * getTableSpecifications (PGconn * conn, const char * tableName)
Pega as especificações de uma tabela,recebendo a conexão e o nome da tabela.
References exeQuery().
Referenced by insert(), and showTableSpecifications().
getTablesQuery()
PGresult * getTablesQuery (PGconn * conn)
Essa função busca as tabelas públicas do banco de dados registrado.
Referenced by showTables().
insertData()
void insertData (PGconn * conn, PGresult * res, const char * tableName)
Insere dados em uma tabela do banco de dados.
Solicita ao usuário que insira valores para cada campo da tabela, mostrando o nome e tipo correspondente. Os valores inseridos são concatenados em uma query de inserção e executados no banco de dados. Exibe mensagem de erro em caso de falha na inserção.
References clearBuffer(), and print().
Referenced by insert().
mockConnectionInfo()
ConnectionInfo * mockConnectionInfo ()
Função para mockar os dados de conexão.
References _connectionInfo::database, _connectionInfo::host, _connectionInfo::password, _connectionInfo::port, and _connectionInfo::user.
Referenced by connectDB().
verifyCreateTable()
void verifyCreateTable (PGresult * result, PGconn * connection)
Verifica a criação da tabela.
References print().
Referenced by createNewTable().