Postgres Connection with C: inc/services.h File Reference
services.h File Reference
#include "psql.h"
#include "helpers.h"
#include "/opt/homebrew/opt/libpq/include/libpq-fe.h"
Macros
#define MAX_COLUMNS 10
Functions
void start (void)
Essa é a função responsável por iniciar o programa.
void options (PGconn *conn)
A função options recebe o status da conexão do banco de dados e da ao usuário as opções de execução do programa.
void showTables (PGconn *conn)
Exibe a lista de tabelas do banco de dados.
void showTableSpecifications (PGconn *conn, const char *tableName)
Recebe como parâmetro a conexão e o nome da tabela e printa na tela as colunas da tabela e as devidas especificações.
void createNewTable (PGconn *conn)
Cria uma nova tabela.
void insert (PGconn *conn)
Função para poder adicionar.
void showTable (PGconn *conn)
Função para fazer um select com filtro.
void displayQueryResult (PGresult *res)
Função para exibir o resultado da query.
void delete (PGconn *conn)
Delete function.
void checkDeleteResult (PGresult *res)
Função para checkar se a query de delete foi bem sucedida.
Macro Definition Documentation
MAX_COLUMNS
#define MAX_COLUMNS 10
Function Documentation
checkDeleteResult()
void checkDeleteResult (PGresult * res)
Função para checkar se a query de delete foi bem sucedida.
References print().
Referenced by delete().
createNewTable()
void createNewTable (PGconn * conn)
Cria uma nova tabela.
References clearBuffer(), exeQuery(), getColumns(), getRowNumber(), getString(), makeQuery(), print(), and verifyCreateTable().
Referenced by options().
delete()
void delete (PGconn * conn)
Delete function.
References buildDeleteQueryWithFilter(), checkDeleteResult(), exeQuery(), getString(), and print().
displayQueryResult()
void displayQueryResult (PGresult * res)
Função para exibir o resultado da query.
Referenced by showTable().
insert()
void insert (PGconn * conn)
Função para poder adicionar.
References getString(), getTableSpecifications(), and insertData().
Referenced by options().
options()
void options (PGconn * conn)
A função options recebe o status da conexão do banco de dados e da ao usuário as opções de execução do programa.
References closeConnection(), createNewTable(), getString(), insert(), print(), printLine(), showTable(), showTables(), and showTableSpecifications().
Referenced by start().
showTable()
void showTable (PGconn * conn)
Função para fazer um select com filtro.
References buildQueryWithFilter(), displayQueryResult(), exeQuery(), getString(), and print().
Referenced by options().
showTables()
void showTables (PGconn * conn)
Exibe a lista de tabelas do banco de dados.
Executa uma consulta SQL para obter os nomes das tabelas do esquema "public" e exibe-os.
Parameters
conn Ponteiro para uma conexão com o banco de dados.
References getTablesQuery(), and print().
Referenced by options().
showTableSpecifications()
void showTableSpecifications (PGconn * conn, const char * tableName)
Recebe como parâmetro a conexão e o nome da tabela e printa na tela as colunas da tabela e as devidas especificações.
References getTableSpecifications(), and print().
Referenced by options().
start()
void start (void)
Essa é a função responsável por iniciar o programa.
References connectDB(), options(), print(), and printLine().
Referenced by main().